In [1]:
import selenium
import pandas as pd
from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException
import time

In [2]:
#importing chromedriver
driver = webdriver.Chrome(r"C:\Users\ashis\Downloads\chromedriver_win32 (1)\chromedriver.exe")

In [3]:
location = []
Company = []
Model = []
ModelType = []
Year = []
Kms      = []
Fuel     = []
Car_Type = []
Color = []
No_of_owner = []
RTO      = []
Transmission = []
Insurance = []
Price = []

In [4]:
def process(url):    
    driver.implicitly_wait(2)
    try:
        SCROLL_PAUSE_TIME = 0.5
        driver.get(url)
        last_height = driver.execute_script("return document.body.scrollHeight")
        while True:
            driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
            time.sleep(SCROLL_PAUSE_TIME)
            new_height = driver.execute_script("return document.body.scrollHeight")
            if new_height == last_height:
                break
            last_height = new_height
        urls = []
        url_link=driver.find_elements_by_xpath("//table[@class='grid-12 omega alpha card-detail-block__data-table']/tbody/tr/td/h2/a")#collecting urls
        for i in url_link:
            urls.append(i.get_attribute('href'))
    finally:
        print("Done")
        
    for i in urls:
        driver.get(i)
        time.sleep(2)
        loc=driver.find_element_by_xpath("//ul[@class='special-skin-text']/li[3]/a/span") #item name
        location.append(loc.text)
        com=driver.find_element_by_xpath("//ul[@class='special-skin-text']/li[4]/a/span") #item name
        Company.append(com.text)
        mod=driver.find_element_by_xpath("//ul[@class='special-skin-text']/li[5]/a/span") #item name
        Model.append(mod.text)
        modtype=driver.find_element_by_xpath("//ul[@class='special-skin-text']/li[6]/span[2]") #item name
        ModelType.append(modtype.text)
        yer=driver.find_element_by_xpath("//ul[@class='basic-details']/li[1]/span[2]") #item name
        Year.append(yer.text)
        km=driver.find_element_by_xpath("//ul[@class='basic-details']/li[2]/span[2]") #item name
        Kms.append(km.text)
        ful=driver.find_element_by_xpath("//ul[@class='basic-details']/li[3]/span[2]") #item name
        Fuel.append(ful.text)
        crtype=driver.find_element_by_xpath("//ul[@class='basic-details']/li[4]/span[2]") #item name
        Car_Type.append(crtype.text)
        trans=driver.find_element_by_xpath("//div[@class='cw-tabs-data']/div/ul/li[5]/div[2]") #item name
        Transmission.append(trans.text)
        col=driver.find_element_by_xpath("//div[@class='cw-tabs-data']/div/ul/li[7]/div[2]") #item name
        Color.append(col.text)
        owner=driver.find_element_by_xpath("//div[@class='cw-tabs-data']/div/ul/li[9]/div[2]") #item name
        No_of_owner.append(owner.text)
        rto=driver.find_element_by_xpath("//div[@class='cw-tabs-data']/div/ul/li[10]/div[2]") #item name
        RTO.append(rto.text)
        ins=driver.find_element_by_xpath("//div[@class='cw-tabs-data']/div/ul/li[11]/div[2]") #item name
        Insurance.append(ins.text)
        MRP=driver.find_element_by_xpath("//div[@class='cw-used-cardetails__price-offer']/p") #item name
        Price.append(MRP.text)

In [5]:
lst = [3001,3000,40,10,2,176,198,128,12,105,246,224,220,225,160,244,143,222,148,280]
for i in lst:
    url = "https://www.carwale.com/used/cars-for-sale/#sc=-1&so=-1&city="+str(i)+"&pc=+"+str(i)
    process(url)

Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done
Done

In [6]:
Car=pd.DataFrame({}) #Dataframe
Car['location'] = location
Car['Company'] = Company
Car['Model'] = Model
Car['ModelType'] = ModelType
Car['Year'] = Year
Car['Kms'] = Kms
Car['Fuel'] = Fuel
Car['Car_Type'] = Car_Type
Car['Transmission'] = Transmission
Car['Color'] = Color
Car['No_of_owner'] = No_of_owner
Car['RTO'] = RTO
Car['Insurance'] = Insurance
Car['Price'] = Price
Car

,location,Company,Model,ModelType,Year,Kms,Fuel,Car_Type,Transmission,Color,No_of_owner,RTO,Insurance,Price
0,Kolkata,Honda,WR-V,VX MT Petrol,May 2018,"37,130",Petrol,Manual,Manual,Black,First,Howrah,Not Available,₹ 7.4 Lakh
1,Surat,Mahindra,XUV500,W8,Jun 2013,"89,000",Diesel,Manual,Manual,Purple,First,Not Available,Not Available,₹ 6.5 Lakh
2,Hyderabad,Nissan,Sunny,XV,Jun 2012,"75,531",Petrol,Manual,Manual,White,Second,Not Available,Not Available,₹ 3.75 Lakh
3,Chennai,Audi,A4,35 TDI Technology,Sep 2018,"96,000",Diesel,Automatic,Automatic,Black,First,Not Available,"Comprehensive , till 04 Dec 2021",₹ 24 Lakh
4,Hyderabad,Mahindra,TUV300,T6 Plus,Jan 2016,"1,47,500",Diesel,Manual,Manual,White,First,Not Available,Not Available,₹ 5.9 Lakh
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2360,Mumbai,Toyota,Fortuner,3.0 MT,Feb 2010,"1,20,000",Diesel,Manual,Manual,White,Second,Not Available,Not Available,₹ 9.25 Lakh
2361,Mumbai,Volkswagen,Polo,GT TSI,Aug 2016,"40,000",Petrol,Automatic,Automatic,Black,Second,Not Available,"Comprehensive , till 20 May 2022",₹ 6.5 Lakh
2362,Mumbai,Maruti Suzuki,Swift DZire,ZDI AMT,Jul 2017,"39,000",Diesel,Automatic,Automatic,Red,First,Not Available,Not Available,₹ 8.25 Lakh
2363,Delhi,Audi,A3,35 TDI Premium Plus,Apr 2018,"20,000",Diesel,Automatic,Automatic,Red,First,Not Available,Not Available,₹ 26 Lakh
2364,Delhi,BMW,X5,xDrive 30d,Jun 2014,"50,000",Diesel,Automatic,Automatic,Blue,First,Not Available,Not Available,₹ 29.5 Lakh

In [7]:
df = pd.DataFrame(Car)
df.to_csv('Cars.CSV', index=False)

In [8]:
def process_car(url):
    #url = 'https://www.olx.in/maharashtra_g2001163/cars_c84/q-old-car' #getting the required url
    location = []
    Company = []
    Model = []
    ModelType = []
    Year = []
    Kms      = []
    Fuel     = []
    Color = []
    No_of_owner = []
    RTO      = []
    Transmission = []
    Insurance = []
    Price = []
    driver.get(url)
    time.sleep(5)
    for i in range(1,15):
        try:
            load_more = driver.find_element_by_xpath("//button[@class='rui-39-wj rui-3evoE rui-1JPTg']") #submit button
            load_more.click() #submitting the input
        except NoSuchElementException as e:
            break
    time.sleep(2)
    urls = []
    url_link=driver.find_elements_by_xpath("//ul[@class='rl3f9 _3mXOU']/li/a")#collecting urls
    for i in url_link:
        urls.append(i.get_attribute('href'))

    for i in urls:
        driver.get(i)
        time.sleep(2)

        com=driver.find_elements_by_xpath("//section[@class='CBG3S']/div/div/div/div/div/div/span[1]") #item name
        tokens = [0] * 8
        for i in range(1,len(com)+1):
            Detail=driver.find_element_by_xpath("//section[@class='CBG3S']/div/div/div/div/div["+str(i)+"]/div/span[1]")
            Value=driver.find_element_by_xpath("//section[@class='CBG3S']/div/div/div/div/div["+str(i)+"]/div/span[2]")
            if(Detail.text == "Brand"):
                Company.append(Value.text)
                tokens[0] = 1
            if(Detail.text == "Model"):
                Model.append(Value.text)
                tokens[1] = 1
            if(Detail.text == "Variant"):
                ModelType.append(Value.text)
                tokens[2] = 1
            if(Detail.text == "Year"):
                Year.append(Value.text)
                tokens[3] = 1
            if(Detail.text == "Fuel"):
                Fuel.append(Value.text)
                tokens[4] = 1
            if(Detail.text == "Transmission"):
                Transmission.append(Value.text)
                tokens[5] = 1
            if(Detail.text == "KM driven"):
                Kms.append(Value.text)
                tokens[6] = 1
            if(Detail.text == "No. of Owners"):
                No_of_owner.append(Value.text)
                tokens[7] = 1
        if(tokens[0] == 0):
            Company.append("Not Available")
        if(tokens[1] == 0):
            Model.append("Not Available")
        if(tokens[2] == 0):
            ModelType.append("Not Available")
        if(tokens[3] == 0):
            Year.append("Not Available")
        if(tokens[4] == 0):
            Fuel.append("Not Available")
        if(tokens[5] == 0):
            Transmission.append("Not Available")
        if(tokens[6] == 0):
            Kms.append("Not Available")
        if(tokens[7] == 0):
            No_of_owner.append("Not Available")

        try:
            MRP=driver.find_element_by_xpath("//div[@class='rui-eJl9O rui-wybRG rui-30Sko rui-27muF rui-2MigZ rui-33FUR']/div[1]/div/section/span[1]")
            Price.append(MRP.text)
        except:
            Price.append("Not Available")

        try:
            loc=driver.find_element_by_xpath("//div[@class='rui-eJl9O rui-wybRG rui-30Sko rui-27muF rui-2MigZ rui-33FUR']/div[1]/div/section/div/div[1]/div/span")
            location.append(loc.text)
        except:
            location.append("Not Available")


        com=driver.find_elements_by_xpath("//section[@class='CBG3S']/div/div/div[2]/p") #item name
        token = [0] * 3
        for i in range(1,len(com)+1):
            Detail=driver.find_element_by_xpath("//section[@class='CBG3S']/div/div/div[2]/p["+str(i)+"]")
            if (Detail.text.find("Color:") != -1):
                col = Detail.text.split(": ")
                Color.append(col[1])
                token[0] = 1
            if (Detail.text.find("Insurance Type:") != -1):
                ins = Detail.text.split(": ")
                Insurance.append(ins[1])
                token[1] = 1
            if (Detail.text.find("Registration Place:") != -1):
                loc = Detail.text.split(": ")
                RTO.append(loc[1])
                token[2] = 1
        if(token[0] == 0):
            Color.append("Not Available")
        if(token[1] == 0):
            Insurance.append("Not Available")
        if(token[2] == 0):
            RTO.append("Not Available")
    global Car1
    Car1=pd.DataFrame({}) #Dataframe
    Car1['location'] = location
    Car1['Company'] = Company
    Car1['Model'] = Model
    Car1['ModelType'] = ModelType
    Car1['Year'] = Year
    Car1['Kms'] = Kms
    Car1['Fuel'] = Fuel
    Car1['Transmission'] = Transmission
    Car1['Color'] = Color
    Car1['No_of_owner'] = No_of_owner
    Car1['RTO'] = RTO
    Car1['Insurance'] = Insurance
    Car1['Price'] = Price
    Car1

In [9]:
process_car('https://www.olx.in/maharashtra_g2001163/cars_c84/q-old-car')

In [10]:
Car1

,location,Company,Model,ModelType,Year,Kms,Fuel,Transmission,Color,No_of_owner,RTO,Insurance,Price
0,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
1,"Prabhadevi, Mumbai, Maharashtra",Mini,Cooper Countryman,S,2018,"17,000 km",Not Available,Not Available,Not Available,1st,MH,Comprehensive,"₹ 35,00,000"
2,"Millat Nagar, Bhiwandi, Maharashtra",Volkswagen,Vento,1.6 Trendline,2011,"88,000 km",Diesel,Manual,Silver,2nd,MH,Third Party,"₹ 2,75,000"
3,"Chembur, Mumbai, Maharashtra",Toyota,Etios,1.5 V,2012,"37,800 km",Petrol,Manual,Blue,1st,MH,Comprehensive,"₹ 3,60,111"
4,"Borivali West, Mumbai, Maharashtra",Toyota,Innova,2.5 V 8 STR,2013,"97,000 km",Diesel,Manual,Gold,1st,MH,No Insurance,"₹ 9,49,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,"Vishrant Wadi, Pune, Maharashtra",Mahindra,Scorpio,2009-2014 EX,2014,"79,000 km",Diesel,Manual,White,1st,MH,Third Party,"₹ 6,00,000"
476,"Mumbai Central, Mumbai, Maharashtra",Maruti Suzuki,Ertiga,ZDI,2015,"70,000 km",Diesel,Manual,White,1st,MH,No Insurance,"₹ 7,99,000"
477,"Mumbai Central, Mumbai, Maharashtra",Hyundai,Creta,1.6 E Plus,2016,"48,403 km",Petrol,Manual,Silver,1st,MH,Comprehensive,"₹ 8,46,000"
478,"Sindhi Society, Mumbai, Maharashtra",Maruti Suzuki,Ertiga,SHVS VDI,2016,"73,000 km",Diesel,Manual,Gold,1st,MH,No Insurance,"₹ 7,75,000"
479,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available

In [11]:
def process_car(url):
    #url = 'https://www.olx.in/maharashtra_g2001163/cars_c84/q-old-car' #getting the required url
    location = []
    Company = []
    Model = []
    ModelType = []
    Year = []
    Kms      = []
    Fuel     = []
    Color = []
    No_of_owner = []
    RTO      = []
    Transmission = []
    Insurance = []
    Price = []
    driver.get(url)
    time.sleep(5)
    for i in range(1,15):
        try:
            load_more = driver.find_element_by_xpath("//button[@class='rui-39-wj rui-3evoE rui-1JPTg']") #submit button
            load_more.click() #submitting the input
        except NoSuchElementException as e:
            break
    time.sleep(2)
    urls = []
    url_link=driver.find_elements_by_xpath("//ul[@class='rl3f9 _3mXOU']/li/a")#collecting urls
    for i in url_link:
        urls.append(i.get_attribute('href'))

    for i in urls:
        driver.get(i)
        time.sleep(2)

        com=driver.find_elements_by_xpath("//section[@class='CBG3S']/div/div/div/div/div/div/span[1]") #item name
        tokens = [0] * 8
        for i in range(1,len(com)+1):
            Detail=driver.find_element_by_xpath("//section[@class='CBG3S']/div/div/div/div/div["+str(i)+"]/div/span[1]")
            Value=driver.find_element_by_xpath("//section[@class='CBG3S']/div/div/div/div/div["+str(i)+"]/div/span[2]")
            if(Detail.text == "Brand"):
                Company.append(Value.text)
                tokens[0] = 1
            if(Detail.text == "Model"):
                Model.append(Value.text)
                tokens[1] = 1
            if(Detail.text == "Variant"):
                ModelType.append(Value.text)
                tokens[2] = 1
            if(Detail.text == "Year"):
                Year.append(Value.text)
                tokens[3] = 1
            if(Detail.text == "Fuel"):
                Fuel.append(Value.text)
                tokens[4] = 1
            if(Detail.text == "Transmission"):
                Transmission.append(Value.text)
                tokens[5] = 1
            if(Detail.text == "KM driven"):
                Kms.append(Value.text)
                tokens[6] = 1
            if(Detail.text == "No. of Owners"):
                No_of_owner.append(Value.text)
                tokens[7] = 1
        if(tokens[0] == 0):
            Company.append("Not Available")
        if(tokens[1] == 0):
            Model.append("Not Available")
        if(tokens[2] == 0):
            ModelType.append("Not Available")
        if(tokens[3] == 0):
            Year.append("Not Available")
        if(tokens[4] == 0):
            Fuel.append("Not Available")
        if(tokens[5] == 0):
            Transmission.append("Not Available")
        if(tokens[6] == 0):
            Kms.append("Not Available")
        if(tokens[7] == 0):
            No_of_owner.append("Not Available")

        try:
            MRP=driver.find_element_by_xpath("//div[@class='rui-eJl9O rui-wybRG rui-30Sko rui-27muF rui-2MigZ rui-33FUR']/div[1]/div/section/span[1]")
            Price.append(MRP.text)
        except:
            Price.append("Not Available")

        try:
            loc=driver.find_element_by_xpath("//div[@class='rui-eJl9O rui-wybRG rui-30Sko rui-27muF rui-2MigZ rui-33FUR']/div[1]/div/section/div/div[1]/div/span")
            location.append(loc.text)
        except:
            location.append("Not Available")


        com=driver.find_elements_by_xpath("//section[@class='CBG3S']/div/div/div[2]/p") #item name
        token = [0] * 3
        for i in range(1,len(com)+1):
            Detail=driver.find_element_by_xpath("//section[@class='CBG3S']/div/div/div[2]/p["+str(i)+"]")
            if (Detail.text.find("Color:") != -1):
                col = Detail.text.split(": ")
                Color.append(col[1])
                token[0] = 1
            if (Detail.text.find("Insurance Type:") != -1):
                ins = Detail.text.split(": ")
                Insurance.append(ins[1])
                token[1] = 1
            if (Detail.text.find("Registration Place:") != -1):
                loc = Detail.text.split(": ")
                RTO.append(loc[1])
                token[2] = 1
        if(token[0] == 0):
            Color.append("Not Available")
        if(token[1] == 0):
            Insurance.append("Not Available")
        if(token[2] == 0):
            RTO.append("Not Available")
    global Car2
    Car2=pd.DataFrame({}) #Dataframe
    Car2['location'] = location
    Car2['Company'] = Company
    Car2['Model'] = Model
    Car2['ModelType'] = ModelType
    Car2['Year'] = Year
    Car2['Kms'] = Kms
    Car2['Fuel'] = Fuel
    Car2['Transmission'] = Transmission
    Car2['Color'] = Color
    Car2['No_of_owner'] = No_of_owner
    Car2['RTO'] = RTO
    Car2['Insurance'] = Insurance
    Car2['Price'] = Price
    Car2

In [12]:
process_car('https://www.olx.in/delhi_g4058659/cars_c84')

In [13]:
Car2

,location,Company,Model,ModelType,Year,Kms,Fuel,Transmission,Color,No_of_owner,RTO,Insurance,Price
0,"Rajouri Garden, Delhi, Delhi",Honda,Civic,1.8 S MT,2007,"80,000 km",Petrol,Manual,Not Available,2nd,Not Available,Not Available,"₹ 1,50,000"
1,"Rajouri Garden, Delhi, Delhi",Honda,Amaze,Not Available,2013,"57,585 km",Diesel,Manual,White,Not Available,DL,Not Available,"₹ 3,20,000"
2,"Pitampura, Delhi, Delhi",Ford,Ecosport,Not Available,2017,"60,149 km",Diesel,Manual,Grey,Not Available,DL,Not Available,"₹ 6,35,000"
3,"Rohini Sector 2, Delhi, Delhi",Maruti Suzuki,Vitara Brezza,VDi AMT,2018,"29,000 km",Diesel,Automatic,Grey,1st,DL,No Insurance,"₹ 8,75,000"
4,"Pitampura, Delhi, Delhi",Hyundai,i20,Sportz Plus,2010,"56,000 km",CNG & Hybrids,Manual,Not Available,1st,Not Available,Not Available,"₹ 2,35,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,"Pitampura, Delhi, Delhi",Ford,Aspire,Others,2015,"62,000 km",Petrol,Manual,White,1st,DL,No Insurance,"₹ 3,75,000"
496,"Rajouri Garden, Delhi, Delhi",Jaguar,XJ,L 5.0 V8,2011,"33,900 km",Petrol,Automatic,Green,2nd,CH,Comprehensive,"₹ 22,90,000"
497,"Rajouri Garden, Delhi, Delhi",Honda,City ZX,CVT,2020,"12,000 km",Petrol,Automatic,Silver,1st,HR,Zero Dep,"₹ 14,95,000"
498,"Raja Garden, Delhi, Delhi",Maruti Suzuki,Swift,VXI,2019,"19,000 km",Petrol,Manual,Other,1st,DL,No Insurance,"₹ 6,25,000"
499,"Ramesh Nagar, Delhi, Delhi",Maruti Suzuki,Wagon R,Pro,2015,"37,000 km",Not Available,Manual,Red,2nd,DL,Comprehensive,"₹ 2,75,000"

In [15]:
def process_car(url):
    #url = 'https://www.olx.in/maharashtra_g2001163/cars_c84/q-old-car' #getting the required url
    location = []
    Company = []
    Model = []
    ModelType = []
    Year = []
    Kms      = []
    Fuel     = []
    Color = []
    No_of_owner = []
    RTO      = []
    Transmission = []
    Insurance = []
    Price = []
    driver.get(url)
    time.sleep(5)
    for i in range(1,15):
        try:
            load_more = driver.find_element_by_xpath("//button[@class='rui-39-wj rui-3evoE rui-1JPTg']") #submit button
            load_more.click() #submitting the input
        except NoSuchElementException as e:
            break
    time.sleep(2)
    urls = []
    url_link=driver.find_elements_by_xpath("//ul[@class='rl3f9 _3mXOU']/li/a")#collecting urls
    for i in url_link:
        urls.append(i.get_attribute('href'))

    for i in urls:
        driver.get(i)
        time.sleep(2)

        com=driver.find_elements_by_xpath("//section[@class='CBG3S']/div/div/div/div/div/div/span[1]") #item name
        tokens = [0] * 8
        for i in range(1,len(com)+1):
            Detail=driver.find_element_by_xpath("//section[@class='CBG3S']/div/div/div/div/div["+str(i)+"]/div/span[1]")
            Value=driver.find_element_by_xpath("//section[@class='CBG3S']/div/div/div/div/div["+str(i)+"]/div/span[2]")
            if(Detail.text == "Brand"):
                Company.append(Value.text)
                tokens[0] = 1
            if(Detail.text == "Model"):
                Model.append(Value.text)
                tokens[1] = 1
            if(Detail.text == "Variant"):
                ModelType.append(Value.text)
                tokens[2] = 1
            if(Detail.text == "Year"):
                Year.append(Value.text)
                tokens[3] = 1
            if(Detail.text == "Fuel"):
                Fuel.append(Value.text)
                tokens[4] = 1
            if(Detail.text == "Transmission"):
                Transmission.append(Value.text)
                tokens[5] = 1
            if(Detail.text == "KM driven"):
                Kms.append(Value.text)
                tokens[6] = 1
            if(Detail.text == "No. of Owners"):
                No_of_owner.append(Value.text)
                tokens[7] = 1
        if(tokens[0] == 0):
            Company.append("Not Available")
        if(tokens[1] == 0):
            Model.append("Not Available")
        if(tokens[2] == 0):
            ModelType.append("Not Available")
        if(tokens[3] == 0):
            Year.append("Not Available")
        if(tokens[4] == 0):
            Fuel.append("Not Available")
        if(tokens[5] == 0):
            Transmission.append("Not Available")
        if(tokens[6] == 0):
            Kms.append("Not Available")
        if(tokens[7] == 0):
            No_of_owner.append("Not Available")

        try:
            MRP=driver.find_element_by_xpath("//div[@class='rui-eJl9O rui-wybRG rui-30Sko rui-27muF rui-2MigZ rui-33FUR']/div[1]/div/section/span[1]")
            Price.append(MRP.text)
        except:
            Price.append("Not Available")

        try:
            loc=driver.find_element_by_xpath("//div[@class='rui-eJl9O rui-wybRG rui-30Sko rui-27muF rui-2MigZ rui-33FUR']/div[1]/div/section/div/div[1]/div/span")
            location.append(loc.text)
        except:
            location.append("Not Available")


        com=driver.find_elements_by_xpath("//section[@class='CBG3S']/div/div/div[2]/p") #item name
        token = [0] * 3
        for i in range(1,len(com)+1):
            Detail=driver.find_element_by_xpath("//section[@class='CBG3S']/div/div/div[2]/p["+str(i)+"]")
            if (Detail.text.find("Color:") != -1):
                col = Detail.text.split(": ")
                Color.append(col[1])
                token[0] = 1
            if (Detail.text.find("Insurance Type:") != -1):
                ins = Detail.text.split(": ")
                Insurance.append(ins[1])
                token[1] = 1
            if (Detail.text.find("Registration Place:") != -1):
                loc = Detail.text.split(": ")
                RTO.append(loc[1])
                token[2] = 1
        if(token[0] == 0):
            Color.append("Not Available")
        if(token[1] == 0):
            Insurance.append("Not Available")
        if(token[2] == 0):
            RTO.append("Not Available")
    global Car3
    Car3=pd.DataFrame({}) #Dataframe
    Car3['location'] = location
    Car3['Company'] = Company
    Car3['Model'] = Model
    Car3['ModelType'] = ModelType
    Car3['Year'] = Year
    Car3['Kms'] = Kms
    Car3['Fuel'] = Fuel
    Car3['Transmission'] = Transmission
    Car3['Color'] = Color
    Car3['No_of_owner'] = No_of_owner
    Car3['RTO'] = RTO
    Car3['Insurance'] = Insurance
    Car3['Price'] = Price
    Car3

In [16]:
process_car('https://www.olx.in/jaipur_g4059123/cars_c84')

In [17]:
Car3

,location,Company,Model,ModelType,Year,Kms,Fuel,Transmission,Color,No_of_owner,RTO,Insurance,Price
0,"Vaishali Nagar, Jaipur, Rajasthan",Mahindra,XUV500,2011-2015 W8 2WD,2012,"79,000 km",Diesel,Manual,White,2nd,RJ,Comprehensive,"₹ 5,50,000"
1,"Everest Vihar, Jaipur, Rajasthan",Skoda,Rapid,1.5 TDI CR Elegance Plus,2014,"73,000 km",Diesel,Manual,Silver,1st,RJ,Comprehensive,"₹ 5,50,000"
2,"Jaman Nagar, Jaipur, Rajasthan",Maruti Suzuki,Vitara Brezza,ZDi Plus,2019,"45,000 km",Diesel,Manual,White,1st,RJ,Comprehensive,"₹ 9,95,000"
3,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
4,"Sikar Road, Jaipur, Rajasthan",Mahindra,Scorpio,S11,2018,"84,000 km",Diesel,Manual,White,1st,RJ,Comprehensive,"₹ 14,50,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,"Vardhman Nagar, Jaipur, Rajasthan",Hyundai,i10,Magna,2008,"92,400 km",Petrol,Manual,Red,2nd,RJ,Comprehensive,"₹ 1,50,000"
496,"Jaisinghpura, Jaipur, Rajasthan",Hyundai,Grand i10,Not Available,2018,"50,067 km",Petrol,Manual,Not Available,Not Available,Not Available,No Insurance,"₹ 4,96,325"
497,"Nirman Nagar, Jaipur, Rajasthan",Hyundai,Grand i10,Not Available,2016,"19,179 km",Petrol,Manual,Silver,Not Available,RJ,Comprehensive,"₹ 5,90,000"
498,"Jaisinghpura, Jaipur, Rajasthan",Hyundai,Grand i10,Not Available,2018,"25,319 km",Petrol,Manual,White,Not Available,Not Available,No Insurance,"₹ 5,25,500"
499,"Jaisinghpura, Jaipur, Rajasthan",Toyota,Etios Liva,Not Available,2012,"112,486 km",Diesel,Manual,White,Not Available,Not Available,No Insurance,"₹ 3,45,700"

In [18]:
def process_car4(url):
    #url = 'https://www.olx.in/maharashtra_g2001163/cars_c84/q-old-car' #getting the required url
    location = []
    Company = []
    Model = []
    ModelType = []
    Year = []
    Kms      = []
    Fuel     = []
    Color = []
    No_of_owner = []
    RTO      = []
    Transmission = []
    Insurance = []
    Price = []
    driver.get(url)
    time.sleep(5)
    for i in range(1,15):
        try:
            load_more = driver.find_element_by_xpath("//button[@class='rui-39-wj rui-3evoE rui-1JPTg']") #submit button
            load_more.click() #submitting the input
        except NoSuchElementException as e:
            break
    time.sleep(2)
    urls = []
    url_link=driver.find_elements_by_xpath("//ul[@class='rl3f9 _3mXOU']/li/a")#collecting urls
    for i in url_link:
        urls.append(i.get_attribute('href'))

    for i in urls:
        driver.get(i)
        time.sleep(2)

        com=driver.find_elements_by_xpath("//section[@class='CBG3S']/div/div/div/div/div/div/span[1]") #item name
        tokens = [0] * 8
        for i in range(1,len(com)+1):
            Detail=driver.find_element_by_xpath("//section[@class='CBG3S']/div/div/div/div/div["+str(i)+"]/div/span[1]")
            Value=driver.find_element_by_xpath("//section[@class='CBG3S']/div/div/div/div/div["+str(i)+"]/div/span[2]")
            if(Detail.text == "Brand"):
                Company.append(Value.text)
                tokens[0] = 1
            if(Detail.text == "Model"):
                Model.append(Value.text)
                tokens[1] = 1
            if(Detail.text == "Variant"):
                ModelType.append(Value.text)
                tokens[2] = 1
            if(Detail.text == "Year"):
                Year.append(Value.text)
                tokens[3] = 1
            if(Detail.text == "Fuel"):
                Fuel.append(Value.text)
                tokens[4] = 1
            if(Detail.text == "Transmission"):
                Transmission.append(Value.text)
                tokens[5] = 1
            if(Detail.text == "KM driven"):
                Kms.append(Value.text)
                tokens[6] = 1
            if(Detail.text == "No. of Owners"):
                No_of_owner.append(Value.text)
                tokens[7] = 1
        if(tokens[0] == 0):
            Company.append("Not Available")
        if(tokens[1] == 0):
            Model.append("Not Available")
        if(tokens[2] == 0):
            ModelType.append("Not Available")
        if(tokens[3] == 0):
            Year.append("Not Available")
        if(tokens[4] == 0):
            Fuel.append("Not Available")
        if(tokens[5] == 0):
            Transmission.append("Not Available")
        if(tokens[6] == 0):
            Kms.append("Not Available")
        if(tokens[7] == 0):
            No_of_owner.append("Not Available")

        try:
            MRP=driver.find_element_by_xpath("//div[@class='rui-eJl9O rui-wybRG rui-30Sko rui-27muF rui-2MigZ rui-33FUR']/div[1]/div/section/span[1]")
            Price.append(MRP.text)
        except:
            Price.append("Not Available")

        try:
            loc=driver.find_element_by_xpath("//div[@class='rui-eJl9O rui-wybRG rui-30Sko rui-27muF rui-2MigZ rui-33FUR']/div[1]/div/section/div/div[1]/div/span")
            location.append(loc.text)
        except:
            location.append("Not Available")


        com=driver.find_elements_by_xpath("//section[@class='CBG3S']/div/div/div[2]/p") #item name
        token = [0] * 3
        for i in range(1,len(com)+1):
            Detail=driver.find_element_by_xpath("//section[@class='CBG3S']/div/div/div[2]/p["+str(i)+"]")
            if (Detail.text.find("Color:") != -1):
                col = Detail.text.split(": ")
                Color.append(col[1])
                token[0] = 1
            if (Detail.text.find("Insurance Type:") != -1):
                ins = Detail.text.split(": ")
                Insurance.append(ins[1])
                token[1] = 1
            if (Detail.text.find("Registration Place:") != -1):
                loc = Detail.text.split(": ")
                RTO.append(loc[1])
                token[2] = 1
        if(token[0] == 0):
            Color.append("Not Available")
        if(token[1] == 0):
            Insurance.append("Not Available")
        if(token[2] == 0):
            RTO.append("Not Available")
    global Car4
    Car4=pd.DataFrame({}) #Dataframe
    Car4['location'] = location
    Car4['Company'] = Company
    Car4['Model'] = Model
    Car4['ModelType'] = ModelType
    Car4['Year'] = Year
    Car4['Kms'] = Kms
    Car4['Fuel'] = Fuel
    Car4['Transmission'] = Transmission
    Car4['Color'] = Color
    Car4['No_of_owner'] = No_of_owner
    Car4['RTO'] = RTO
    Car4['Insurance'] = Insurance
    Car4['Price'] = Price
    Car4

In [19]:
process_car4('https://www.olx.in/chennai_g4059162/cars_c84')

In [20]:
Car4

,location,Company,Model,ModelType,Year,Kms,Fuel,Transmission,Color,No_of_owner,RTO,Insurance,Price
0,"Thousand Lights, Chennai, Tamil Nadu",Maruti Suzuki,Baleno,1.2 Delta,2019,"62,000 km",Petrol,Manual,White,1st,TN,Comprehensive,"₹ 6,90,000"
1,"Perambur, Chennai, Tamil Nadu",Renault,KWID,1.0 RXT,2017,"51,000 km",Petrol,Manual,Red,1st,TN,No Insurance,"₹ 3,65,000"
2,"Chennai Central, Chennai, Tamil Nadu",Tata,Indigo CS,CS GLX,2010,"21,000 km",Petrol,Manual,Bordeaux/Maroon,1st,TN,No Insurance,"₹ 2,10,000"
3,"Chennai Central, Chennai, Tamil Nadu",Hyundai,i10,1.2 Kappa SPORTZ,2013,"48,000 km",Petrol,Manual,Grey,1st,TN,Comprehensive,"₹ 3,75,000"
4,"Chennai Central, Chennai, Tamil Nadu",Maruti Suzuki,A-Star,AT VXI,2013,"64,000 km",Petrol,Automatic,Blue,1st,TN,Comprehensive,"₹ 3,20,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,"Nungambakkam, Chennai, Tamil Nadu",Honda,CR-V,2007-2012 2.4 MT,2007,"80,000 km",Petrol,Manual,Black,1st,TN,Comprehensive,"₹ 3,80,000"
496,"Nungambakkam, Chennai, Tamil Nadu",Hyundai,i20,2010-2012 1.2 Sportz,2012,"45,000 km",Petrol,Manual,Silver,1st,TN,Comprehensive,"₹ 4,29,000"
497,"Nungambakkam, Chennai, Tamil Nadu",Hyundai,Grand i10,Sportz 1.2 Kappa VTVT,2014,"34,000 km",Petrol,Manual,Gold,1st,TN,Comprehensive,"₹ 4,39,000"
498,"Nungambakkam, Chennai, Tamil Nadu",Honda,Brio,V Automatic,2016,"37,000 km",Petrol,Automatic,Brown,1st,TN,Comprehensive,"₹ 4,99,999"
499,"Nungambakkam, Chennai, Tamil Nadu",Maruti Suzuki,Celerio,ZXI AMT,2017,"15,000 km",Petrol,Automatic,Blue,1st,TN,Comprehensive,"₹ 4,94,000"

In [21]:
def process_car5(url):
    #url = 'https://www.olx.in/maharashtra_g2001163/cars_c84/q-old-car' #getting the required url
    location = []
    Company = []
    Model = []
    ModelType = []
    Year = []
    Kms      = []
    Fuel     = []
    Color = []
    No_of_owner = []
    RTO      = []
    Transmission = []
    Insurance = []
    Price = []
    driver.get(url)
    time.sleep(5)
    for i in range(1,15):
        try:
            load_more = driver.find_element_by_xpath("//button[@class='rui-39-wj rui-3evoE rui-1JPTg']") #submit button
            load_more.click() #submitting the input
        except NoSuchElementException as e:
            break
    time.sleep(2)
    urls = []
    url_link=driver.find_elements_by_xpath("//ul[@class='rl3f9 _3mXOU']/li/a")#collecting urls
    for i in url_link:
        urls.append(i.get_attribute('href'))

    for i in urls:
        driver.get(i)
        time.sleep(2)

        com=driver.find_elements_by_xpath("//section[@class='CBG3S']/div/div/div/div/div/div/span[1]") #item name
        tokens = [0] * 8
        for i in range(1,len(com)+1):
            Detail=driver.find_element_by_xpath("//section[@class='CBG3S']/div/div/div/div/div["+str(i)+"]/div/span[1]")
            Value=driver.find_element_by_xpath("//section[@class='CBG3S']/div/div/div/div/div["+str(i)+"]/div/span[2]")
            if(Detail.text == "Brand"):
                Company.append(Value.text)
                tokens[0] = 1
            if(Detail.text == "Model"):
                Model.append(Value.text)
                tokens[1] = 1
            if(Detail.text == "Variant"):
                ModelType.append(Value.text)
                tokens[2] = 1
            if(Detail.text == "Year"):
                Year.append(Value.text)
                tokens[3] = 1
            if(Detail.text == "Fuel"):
                Fuel.append(Value.text)
                tokens[4] = 1
            if(Detail.text == "Transmission"):
                Transmission.append(Value.text)
                tokens[5] = 1
            if(Detail.text == "KM driven"):
                Kms.append(Value.text)
                tokens[6] = 1
            if(Detail.text == "No. of Owners"):
                No_of_owner.append(Value.text)
                tokens[7] = 1
        if(tokens[0] == 0):
            Company.append("Not Available")
        if(tokens[1] == 0):
            Model.append("Not Available")
        if(tokens[2] == 0):
            ModelType.append("Not Available")
        if(tokens[3] == 0):
            Year.append("Not Available")
        if(tokens[4] == 0):
            Fuel.append("Not Available")
        if(tokens[5] == 0):
            Transmission.append("Not Available")
        if(tokens[6] == 0):
            Kms.append("Not Available")
        if(tokens[7] == 0):
            No_of_owner.append("Not Available")

        try:
            MRP=driver.find_element_by_xpath("//div[@class='rui-eJl9O rui-wybRG rui-30Sko rui-27muF rui-2MigZ rui-33FUR']/div[1]/div/section/span[1]")
            Price.append(MRP.text)
        except:
            Price.append("Not Available")

        try:
            loc=driver.find_element_by_xpath("//div[@class='rui-eJl9O rui-wybRG rui-30Sko rui-27muF rui-2MigZ rui-33FUR']/div[1]/div/section/div/div[1]/div/span")
            location.append(loc.text)
        except:
            location.append("Not Available")


        com=driver.find_elements_by_xpath("//section[@class='CBG3S']/div/div/div[2]/p") #item name
        token = [0] * 3
        for i in range(1,len(com)+1):
            Detail=driver.find_element_by_xpath("//section[@class='CBG3S']/div/div/div[2]/p["+str(i)+"]")
            if (Detail.text.find("Color:") != -1):
                col = Detail.text.split(": ")
                Color.append(col[1])
                token[0] = 1
            if (Detail.text.find("Insurance Type:") != -1):
                ins = Detail.text.split(": ")
                Insurance.append(ins[1])
                token[1] = 1
            if (Detail.text.find("Registration Place:") != -1):
                loc = Detail.text.split(": ")
                RTO.append(loc[1])
                token[2] = 1
        if(token[0] == 0):
            Color.append("Not Available")
        if(token[1] == 0):
            Insurance.append("Not Available")
        if(token[2] == 0):
            RTO.append("Not Available")
    global Car5
    Car5=pd.DataFrame({}) #Dataframe
    Car5['location'] = location
    Car5['Company'] = Company
    Car5['Model'] = Model
    Car5['ModelType'] = ModelType
    Car5['Year'] = Year
    Car5['Kms'] = Kms
    Car5['Fuel'] = Fuel
    Car5['Transmission'] = Transmission
    Car5['Color'] = Color
    Car5['No_of_owner'] = No_of_owner
    Car5['RTO'] = RTO
    Car5['Insurance'] = Insurance
    Car5['Price'] = Price
    Car5

In [23]:
process_car5('https://www.olx.in/assam_g2001147/cars_c84')

In [24]:
def process_car6(url):
    #url = 'https://www.olx.in/maharashtra_g2001163/cars_c84/q-old-car' #getting the required url
    location = []
    Company = []
    Model = []
    ModelType = []
    Year = []
    Kms      = []
    Fuel     = []
    Color = []
    No_of_owner = []
    RTO      = []
    Transmission = []
    Insurance = []
    Price = []
    driver.get(url)
    time.sleep(5)
    for i in range(1,15):
        try:
            load_more = driver.find_element_by_xpath("//button[@class='rui-39-wj rui-3evoE rui-1JPTg']") #submit button
            load_more.click() #submitting the input
        except NoSuchElementException as e:
            break
    time.sleep(2)
    urls = []
    url_link=driver.find_elements_by_xpath("//ul[@class='rl3f9 _3mXOU']/li/a")#collecting urls
    for i in url_link:
        urls.append(i.get_attribute('href'))

    for i in urls:
        driver.get(i)
        time.sleep(2)

        com=driver.find_elements_by_xpath("//section[@class='CBG3S']/div/div/div/div/div/div/span[1]") #item name
        tokens = [0] * 8
        for i in range(1,len(com)+1):
            Detail=driver.find_element_by_xpath("//section[@class='CBG3S']/div/div/div/div/div["+str(i)+"]/div/span[1]")
            Value=driver.find_element_by_xpath("//section[@class='CBG3S']/div/div/div/div/div["+str(i)+"]/div/span[2]")
            if(Detail.text == "Brand"):
                Company.append(Value.text)
                tokens[0] = 1
            if(Detail.text == "Model"):
                Model.append(Value.text)
                tokens[1] = 1
            if(Detail.text == "Variant"):
                ModelType.append(Value.text)
                tokens[2] = 1
            if(Detail.text == "Year"):
                Year.append(Value.text)
                tokens[3] = 1
            if(Detail.text == "Fuel"):
                Fuel.append(Value.text)
                tokens[4] = 1
            if(Detail.text == "Transmission"):
                Transmission.append(Value.text)
                tokens[5] = 1
            if(Detail.text == "KM driven"):
                Kms.append(Value.text)
                tokens[6] = 1
            if(Detail.text == "No. of Owners"):
                No_of_owner.append(Value.text)
                tokens[7] = 1
        if(tokens[0] == 0):
            Company.append("Not Available")
        if(tokens[1] == 0):
            Model.append("Not Available")
        if(tokens[2] == 0):
            ModelType.append("Not Available")
        if(tokens[3] == 0):
            Year.append("Not Available")
        if(tokens[4] == 0):
            Fuel.append("Not Available")
        if(tokens[5] == 0):
            Transmission.append("Not Available")
        if(tokens[6] == 0):
            Kms.append("Not Available")
        if(tokens[7] == 0):
            No_of_owner.append("Not Available")

        try:
            MRP=driver.find_element_by_xpath("//div[@class='rui-eJl9O rui-wybRG rui-30Sko rui-27muF rui-2MigZ rui-33FUR']/div[1]/div/section/span[1]")
            Price.append(MRP.text)
        except:
            Price.append("Not Available")

        try:
            loc=driver.find_element_by_xpath("//div[@class='rui-eJl9O rui-wybRG rui-30Sko rui-27muF rui-2MigZ rui-33FUR']/div[1]/div/section/div/div[1]/div/span")
            location.append(loc.text)
        except:
            location.append("Not Available")


        com=driver.find_elements_by_xpath("//section[@class='CBG3S']/div/div/div[2]/p") #item name
        token = [0] * 3
        for i in range(1,len(com)+1):
            Detail=driver.find_element_by_xpath("//section[@class='CBG3S']/div/div/div[2]/p["+str(i)+"]")
            if (Detail.text.find("Color:") != -1):
                col = Detail.text.split(": ")
                Color.append(col[1])
                token[0] = 1
            if (Detail.text.find("Insurance Type:") != -1):
                ins = Detail.text.split(": ")
                Insurance.append(ins[1])
                token[1] = 1
            if (Detail.text.find("Registration Place:") != -1):
                loc = Detail.text.split(": ")
                RTO.append(loc[1])
                token[2] = 1
        if(token[0] == 0):
            Color.append("Not Available")
        if(token[1] == 0):
            Insurance.append("Not Available")
        if(token[2] == 0):
            RTO.append("Not Available")
    global Car6
    Car6=pd.DataFrame({}) #Dataframe
    Car6['location'] = location
    Car6['Company'] = Company
    Car6['Model'] = Model
    Car6['ModelType'] = ModelType
    Car6['Year'] = Year
    Car6['Kms'] = Kms
    Car6['Fuel'] = Fuel
    Car6['Transmission'] = Transmission
    Car6['Color'] = Color
    Car6['No_of_owner'] = No_of_owner
    Car6['RTO'] = RTO
    Car6['Insurance'] = Insurance
    Car6['Price'] = Price
    Car6

In [25]:
process_car6('https://www.olx.in/en/dehradun_g4059236/cars_c84')

In [26]:
Car5

Empty DataFrame
Columns: [location, Company, Model, ModelType, Year, Kms, Fuel, Transmission, Color, No_of_owner, RTO, Insurance, Price]
Index: []

In [27]:
Car6

Empty DataFrame
Columns: [location, Company, Model, ModelType, Year, Kms, Fuel, Transmission, Color, No_of_owner, RTO, Insurance, Price]
Index: []

In [28]:
webscraping=pd.concat((Car1,Car2,Car3,Car4),ignore_index=True)
webscraping

,location,Company,Model,ModelType,Year,Kms,Fuel,Transmission,Color,No_of_owner,RTO,Insurance,Price
0,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available,Not Available
1,"Prabhadevi, Mumbai, Maharashtra",Mini,Cooper Countryman,S,2018,"17,000 km",Not Available,Not Available,Not Available,1st,MH,Comprehensive,"₹ 35,00,000"
2,"Millat Nagar, Bhiwandi, Maharashtra",Volkswagen,Vento,1.6 Trendline,2011,"88,000 km",Diesel,Manual,Silver,2nd,MH,Third Party,"₹ 2,75,000"
3,"Chembur, Mumbai, Maharashtra",Toyota,Etios,1.5 V,2012,"37,800 km",Petrol,Manual,Blue,1st,MH,Comprehensive,"₹ 3,60,111"
4,"Borivali West, Mumbai, Maharashtra",Toyota,Innova,2.5 V 8 STR,2013,"97,000 km",Diesel,Manual,Gold,1st,MH,No Insurance,"₹ 9,49,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1975,"Chandmari, Guwahati, Assam",Maruti Suzuki,Baleno,1.2 Delta,2016,"65,000 km",Petrol,Manual,Not Available,2nd,Not Available,Not Available,"₹ 4,70,000"
1976,"Gossaigaon Bazar, Gossaigaon, Assam",Maruti Suzuki,Alto,2005-2010 LXi BSIII,2010,"295,000 km",Petrol,Manual,Not Available,2nd,Not Available,Not Available,"₹ 1,50,000"
1977,"Khudra Khetribarni, Bangaon, Assam",Other Brands,Others,Not Available,2016,"35,000 km",Diesel,Manual,Not Available,1st,Not Available,Not Available,"₹ 3,80,000"
1978,"Naohalia No 3, Duliajan, Assam",Maruti Suzuki,Swift Dzire,VXI,2013,"41,692 km",Petrol,Manual,Not Available,1st,Not Available,Not Available,"₹ 4,50,000"
1979,"Lakhipur Bazaar, Lakhipur Cachar District, Assam",Maruti Suzuki,Others,Others,2016,"75,000 km",Petrol,Manual,Not Available,1st,Not Available,Not Available,"₹ 2,40,000"

In [29]:
#df = pd.DataFrame(webscraping)
webscraping.to_csv('Cars1.CSV', index=False)

In [30]:
def process_car7(url):
    counter = 0
    location = []
    Company = []
    Model = []
    ModelType = []
    Year = []
    Kms      = []
    Fuel     = []
    Color = []
    No_of_owner = []
    RTO      = []
    Transmission = []
    Insurance = []
    Price = []
    driver.get(url)
    time.sleep(5)
    for i in range(1,15):
        try:
            load_more = driver.find_element_by_xpath("//button[@class='rui-39-wj rui-3evoE rui-1JPTg']") #submit button
            load_more.click() #submitting the input
        except NoSuchElementException as e:
            break
    time.sleep(2)
    urls = []
    url_link=driver.find_elements_by_xpath("//ul[@class='rl3f9 _3mXOU']/li/a")#collecting urls
    for i in url_link:
        urls.append(i.get_attribute('href'))

    for i in urls:
        driver.get(i)
        time.sleep(2)
        counter += 1
        if(counter%50 == 0):
            print(counter)
        com=driver.find_elements_by_xpath("//section[@class='CBG3S']/div/div/div/div/div/div/span[1]") #item name
        tokens = [0] * 8
        for i in range(1,len(com)+1):
            Detail=driver.find_element_by_xpath("//section[@class='CBG3S']/div/div/div/div/div["+str(i)+"]/div/span[1]")
            Value=driver.find_element_by_xpath("//section[@class='CBG3S']/div/div/div/div/div["+str(i)+"]/div/span[2]")
            if(Detail.text == "Brand"):
                Company.append(Value.text)
                tokens[0] = 1
            if(Detail.text == "Model"):
                Model.append(Value.text)
                tokens[1] = 1
            if(Detail.text == "Variant"):
                ModelType.append(Value.text)
                tokens[2] = 1
            if(Detail.text == "Year"):
                Year.append(Value.text)
                tokens[3] = 1
            if(Detail.text == "Fuel"):
                Fuel.append(Value.text)
                tokens[4] = 1
            if(Detail.text == "Transmission"):
                Transmission.append(Value.text)
                tokens[5] = 1
            if(Detail.text == "KM driven"):
                Kms.append(Value.text)
                tokens[6] = 1
            if(Detail.text == "No. of Owners"):
                No_of_owner.append(Value.text)
                tokens[7] = 1
        if(tokens[0] == 0):
            Company.append("Not Available")
        if(tokens[1] == 0):
            Model.append("Not Available")
        if(tokens[2] == 0):
            ModelType.append("Not Available")
        if(tokens[3] == 0):
            Year.append("Not Available")
        if(tokens[4] == 0):
            Fuel.append("Not Available")
        if(tokens[5] == 0):
            Transmission.append("Not Available")
        if(tokens[6] == 0):
            Kms.append("Not Available")
        if(tokens[7] == 0):
            No_of_owner.append("Not Available")

        try:
            MRP=driver.find_element_by_xpath("//div[@class='rui-eJl9O rui-wybRG rui-30Sko rui-27muF rui-2MigZ rui-33FUR']/div[1]/div/section/span[1]")
            Price.append(MRP.text)
        except:
            Price.append("Not Available")

        try:
            loc=driver.find_element_by_xpath("//div[@class='rui-eJl9O rui-wybRG rui-30Sko rui-27muF rui-2MigZ rui-33FUR']/div[1]/div/section/div/div[1]/div/span")
            location.append(loc.text)
        except:
            location.append("Not Available")


        com=driver.find_elements_by_xpath("//section[@class='CBG3S']/div/div/div[2]/p") #item name
        token = [0] * 3
        for i in range(1,len(com)+1):
            Detail=driver.find_element_by_xpath("//section[@class='CBG3S']/div/div/div[2]/p["+str(i)+"]")
            if (Detail.text.find("Color:") != -1):
                col = Detail.text.split(": ")
                Color.append(col[1])
                token[0] = 1
            if (Detail.text.find("Insurance Type:") != -1):
                ins = Detail.text.split(": ")
                Insurance.append(ins[1])
                token[1] = 1
            if (Detail.text.find("Registration Place:") != -1):
                loc = Detail.text.split(": ")
                RTO.append(loc[1])
                token[2] = 1
        if(token[0] == 0):
            Color.append("Not Available")
        if(token[1] == 0):
            Insurance.append("Not Available")
        if(token[2] == 0):
            RTO.append("Not Available")
    global Car7
    Car7=pd.DataFrame({}) #Dataframe
    Car7['location'] = location
    Car7['Company'] = Company
    Car7['Model'] = Model
    Car7['ModelType'] = ModelType
    Car7['Year'] = Year
    Car7['Kms'] = Kms
    Car7['Fuel'] = Fuel
    Car7['Transmission'] = Transmission
    Car7['Color'] = Color
    Car7['No_of_owner'] = No_of_owner
    Car7['RTO'] = RTO
    Car7['Insurance'] = Insurance
    Car7['Price'] = Price
    Car7

In [31]:
process_car7('https://www.olx.in/en/dehradun_g4059236/cars_c84')

50
100
150
200
250
300
350
400
450
500

In [32]:
Car7

,location,Company,Model,ModelType,Year,Kms,Fuel,Transmission,Color,No_of_owner,RTO,Insurance,Price
0,"Purvi Patel Nagar, Dehradun, Uttaranchal",Honda,City,2008-2011 1.5 S MT,2009,"52,000 km",Petrol,Manual,Silver,1st,UK,No Insurance,"₹ 3,00,000"
1,"Race Course, Dehradun, Uttaranchal",Tata,Safari,EX 4x2,2009,"77,000 km",Diesel,Manual,White,1st,UK,Not Available,"₹ 2,10,000"
2,"Race Course, Dehradun, Uttaranchal",Volkswagen,Ameo,Not Available,2017,"57,000 km",Petrol,Manual,Blue,1st,UK,Comprehensive,"₹ 4,50,000"
3,"Rajpur Road, Dehradun, Uttaranchal",Toyota,Innova Crysta,2.8 ZX AT,2018,"16,000 km",Diesel,Automatic,Not Available,1st,Not Available,Not Available,"₹ 25,00,000"
4,"Harbans Wala, Dehradun, Uttaranchal",Maruti Suzuki,Ritz,ZXi,2013,"79,000 km",Petrol,Automatic,White,3rd,UK,Comprehensive,"₹ 3,20,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,"Doon IT Park, Dehradun, Uttaranchal",Volkswagen,Polo GTI,Polo GTI,2019,"9,700 km",Petrol,Automatic,Red,1st,UK,Comprehensive,"₹ 8,90,000"
496,"Shahpur, Bhagwanpur, Uttaranchal",Hyundai,Santro Xing,XL,2006,"70,000 km",Petrol,Automatic,Not Available,3rd,Not Available,Not Available,"₹ 90,000"
497,"Majra, Dehradun, Uttaranchal",Hyundai,Santro Xing,Not Available,2007,"45,000 km",Petrol,Manual,Gold,Not Available,UK,No Insurance,"₹ 1,30,000"
498,"Majra, Dehradun, Uttaranchal",Hyundai,Santro Xing,Not Available,2006,"58,769 km",Petrol,Manual,Black,Not Available,UK,Comprehensive,"₹ 1,15,000"
499,"Ranipur, Haridwar, Uttaranchal",Tata,Hexa,XTA,2017,"46,000 km",Diesel,Automatic,Grey,1st,UK,No Insurance,"₹ 13,50,000"

In [33]:
Car7.to_csv('Cars2.CSV', index=False)

In [35]:
def process_car5(url):
    #url = 'https://www.olx.in/maharashtra_g2001163/cars_c84/q-old-car' #getting the required url
    counter = 0
    location = []
    Company = []
    Model = []
    ModelType = []
    Year = []
    Kms      = []
    Fuel     = []
    Color = []
    No_of_owner = []
    RTO      = []
    Transmission = []
    Insurance = []
    Price = []
    driver.get(url)
    time.sleep(5)
    for i in range(1,15):
        try:
            load_more = driver.find_element_by_xpath("//button[@class='rui-39-wj rui-3evoE rui-1JPTg']") #submit button
            load_more.click() #submitting the input
        except NoSuchElementException as e:
            break
    time.sleep(2)
    urls = []
    url_link=driver.find_elements_by_xpath("//ul[@class='rl3f9 _3mXOU']/li/a")#collecting urls
    for i in url_link:
        urls.append(i.get_attribute('href'))

    for i in urls:
        driver.get(i)
        time.sleep(2)
        counter += 1
        if(counter%50 == 0):
            print(counter)
        com=driver.find_elements_by_xpath("//section[@class='CBG3S']/div/div/div/div/div/div/span[1]") #item name
        tokens = [0] * 8
        for i in range(1,len(com)+1):
            Detail=driver.find_element_by_xpath("//section[@class='CBG3S']/div/div/div/div/div["+str(i)+"]/div/span[1]")
            Value=driver.find_element_by_xpath("//section[@class='CBG3S']/div/div/div/div/div["+str(i)+"]/div/span[2]")
            if(Detail.text == "Brand"):
                Company.append(Value.text)
                tokens[0] = 1
            if(Detail.text == "Model"):
                Model.append(Value.text)
                tokens[1] = 1
            if(Detail.text == "Variant"):
                ModelType.append(Value.text)
                tokens[2] = 1
            if(Detail.text == "Year"):
                Year.append(Value.text)
                tokens[3] = 1
            if(Detail.text == "Fuel"):
                Fuel.append(Value.text)
                tokens[4] = 1
            if(Detail.text == "Transmission"):
                Transmission.append(Value.text)
                tokens[5] = 1
            if(Detail.text == "KM driven"):
                Kms.append(Value.text)
                tokens[6] = 1
            if(Detail.text == "No. of Owners"):
                No_of_owner.append(Value.text)
                tokens[7] = 1
        if(tokens[0] == 0):
            Company.append("Not Available")
        if(tokens[1] == 0):
            Model.append("Not Available")
        if(tokens[2] == 0):
            ModelType.append("Not Available")
        if(tokens[3] == 0):
            Year.append("Not Available")
        if(tokens[4] == 0):
            Fuel.append("Not Available")
        if(tokens[5] == 0):
            Transmission.append("Not Available")
        if(tokens[6] == 0):
            Kms.append("Not Available")
        if(tokens[7] == 0):
            No_of_owner.append("Not Available")

        try:
            MRP=driver.find_element_by_xpath("//div[@class='rui-eJl9O rui-wybRG rui-30Sko rui-27muF rui-2MigZ rui-33FUR']/div[1]/div/section/span[1]")
            Price.append(MRP.text)
        except:
            Price.append("Not Available")

        try:
            loc=driver.find_element_by_xpath("//div[@class='rui-eJl9O rui-wybRG rui-30Sko rui-27muF rui-2MigZ rui-33FUR']/div[1]/div/section/div/div[1]/div/span")
            location.append(loc.text)
        except:
            location.append("Not Available")


        com=driver.find_elements_by_xpath("//section[@class='CBG3S']/div/div/div[2]/p") #item name
        token = [0] * 3
        for i in range(1,len(com)+1):
            Detail=driver.find_element_by_xpath("//section[@class='CBG3S']/div/div/div[2]/p["+str(i)+"]")
            if (Detail.text.find("Color:") != -1):
                col = Detail.text.split(": ")
                Color.append(col[1])
                token[0] = 1
            if (Detail.text.find("Insurance Type:") != -1):
                ins = Detail.text.split(": ")
                Insurance.append(ins[1])
                token[1] = 1
            if (Detail.text.find("Registration Place:") != -1):
                loc = Detail.text.split(": ")
                RTO.append(loc[1])
                token[2] = 1
        if(token[0] == 0):
            Color.append("Not Available")
        if(token[1] == 0):
            Insurance.append("Not Available")
        if(token[2] == 0):
            RTO.append("Not Available")
    global Car8
    Car8=pd.DataFrame({}) #Dataframe
    Car8['location'] = location
    Car8['Company'] = Company
    Car8['Model'] = Model
    Car8['ModelType'] = ModelType
    Car8['Year'] = Year
    Car8['Kms'] = Kms
    Car8['Fuel'] = Fuel
    Car8['Transmission'] = Transmission
    Car8['Color'] = Color
    Car8['No_of_owner'] = No_of_owner
    Car8['RTO'] = RTO
    Car8['Insurance'] = Insurance
    Car8['Price'] = Price
    Car8

In [36]:
process_car5('https://www.olx.in/assam_g2001147/cars_c84')

50
100
150
200
250
300
350
400
450
500

In [37]:
Car8

,location,Company,Model,ModelType,Year,Kms,Fuel,Transmission,Color,No_of_owner,RTO,Insurance,Price
0,"Vartak Enclave, Tezpur, Assam",Maruti Suzuki,Swift,VXI,2018,"25,000 km",Petrol,Manual,White,1st,AS,Comprehensive,"₹ 5,50,000"
1,"Hatigaon, Guwahati, Assam",Hyundai,Accent,GLE,2008,"71,000 km",Petrol,Manual,Gold,2nd,AS,Comprehensive,"₹ 1,65,000"
2,"Vartak Enclave, Tezpur, Assam",Maruti Suzuki,Celerio,2014-2017 VXI,2017,"21,000 km",Petrol,Manual,Silver,1st,AS,Comprehensive,"₹ 4,30,000"
3,"Adabari, Guwahati, Assam",Honda,Amaze,1.2 SMT I VTEC,2014,"76,000 km",Petrol,Manual,Blue,1st,AS,Comprehensive,"₹ 3,50,000"
4,"Borjari Maj Gaon, Jamunamukh, Assam",Dc,TCA,Others,2021,"6,000 km",Electric,Automatic,Not Available,1st,Not Available,Not Available,"₹ 90,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,"Bahbari Gaon, Tinsukia, Assam",Mahindra,Scorpio,2002-2013 2.6 SLX CRDe,2004,"100,000 km",Diesel,Automatic,Not Available,2nd,Not Available,Not Available,"₹ 1,85,000"
496,"Lichubari, Jorhat, Assam",Tata,Sumo Grande,Grande LX,2009,"90,000 km",Diesel,Automatic,Not Available,1st,Not Available,Not Available,"₹ 1,90,000"
497,"Madhuban, Jorhat, Assam",Renault,KWID,1.0 RXT,2017,"25,000 km",Petrol,Manual,Not Available,1st,Not Available,Not Available,"₹ 2,75,000"
498,"Amolapatti, Dibrugarh, Assam",Mahindra,Supro,Others,2021,120 km,Diesel,Manual,Not Available,1st,Not Available,Not Available,"₹ 1,70,000"
499,"Khowang, Moranhat, Assam",Renault,Duster,110PS Diesel RxL AMT,2014,"65,000 km",Diesel,Manual,Not Available,1st,Not Available,Not Available,"₹ 5,30,000"

In [38]:
Car8.to_csv('Cars3.CSV', index=False)